name: CI

on: [push]

env:
  YQ_VERSION: "4.25.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
      - run: wget https://github.com/mikefarah/yq/releases/download/v$YQ_VERSION/yq_linux_amd64.tar.gz -O - | tar xz && mv yq_linux_amd64 /usr/local/bin/yq
      - run: yq ".Resources.LogsLambda.Properties.Code.ZipFile = \"$(sed  's/\"/\\\"/g' handler.py)\""  axiom-cloudfront-lambda-cloudformation-stack.template.yaml > axiom-cloudfront-lambda-cloudformation-stack.yaml
      - run: cat axiom-cloudfront-lambda-cloudformation-stack.yaml